### ISSUE TITLE
Implement number theory functions

### ISSUE THREAD

**Issue by vks** [tczajka/ibig-rs#1]
It would be nice to implement some number theory functions such as the extended GCD, the modular inverse and the modular power. See https://github.com/vks/discrete-log/blob/master/src/main.rs for a generic implementation that could probably be implemented more efficiently inside this crate.

**Comment by tczajka** [comment]
- [ ] Modular arithmetic: addition, subtraction, multiplication.
- [ ] Modular inverse, division.
- [ ] Modular exponentiation.
- [ ] Modular exponentiation to signed powers.
- [ ] GCD
- [ ] Extended GCD

**Comment by tczajka** [comment]
There is now direct support for modular arithmetic with the `ModuloRing` type.

**Comment by tczajka** [comment]
All these functions are now implemented.
