### ISSUE TITLE
Expose as_words()

### ISSUE THREAD

**Issue by cmpute** [tczajka/ibig-rs#14]
I personally find it annoying that `num-bigint` didn't expose its internal representation, it will be great if the internal buffer is accessible (even readonly) from outside. This will be useful if other algorithms are to be implemented on ibig (such as algorithms related to modular arithmetics, number theory, rational and float numbers)

**Comment by cmpute** [comment]
It will be even better if `UBig` can accept `Vec<Word>` as an input of constructor, in that case the overhead of copying will be minimized for the external algorithm implementations.

**Comment by tczajka** [comment]
I understand the desire. However, this would limit the implementation. For instance, idea #13 would be outright prevented by this. Plus, `Word` is different on different platforms which may be annoying to users.

There is `to_le_bytes` and `from_le_bytes`, which can easily be converted to `Vec<u64>` or whatnot, perhaps this is sufficient for most algorithms?

Do you have a specific example of an algorithm that would benefit from accessing `Word`s?

**Comment by cmpute** [comment]
> I understand the desire. However, this would limit the implementation. For instance, idea #13 would be outright prevented by this. Plus, `Word` is different on different platforms which may be annoying to users.
> 
> There is `to_le_bytes` and `from_le_bytes`, which can easily be converted to `Vec<u64>` or whatnot, perhaps this is sufficient for most algorithms?
> 
> Do you have a specific example of an algorithm that would benefit from accessing `Word`s?

If we implement inline double word as `&[u64;2]`, then we can take reference from all three enum variants of `Repr`. This is still feasible even if more words are inlined, the difference is just whether the memory behind the reference is on stack or heap.

Indeed I can use `to_le_bytes`/`from_le_bytes`, but the idea is to avoid copying. For example, if I want to implement a exact division algorithm (useful for implementing rational number), it's pretty fast for small integers, and in that case I guess the overhead of copying is not negligible? Montgomery form is another example, which I mentioned in another issue.
