### ISSUE TITLE
Confusing documentation of trailing_zeros

### ISSUE THREAD

**Issue by cmpute** [tczajka/ibig-rs#15]
https://github.com/tczajka/ibig-rs/blob/f1588d8758872db0300a6f5ff1a5a77771c16b6a/src/bits.rs#L213

IBig is not represented in two's complement format, I think it's better to just say "number of trailing zeros in the binary representation of its magnitude"

**Comment by tczajka** [comment]
The internal representation is not exposed, so it is not relevant here.

Many other operations are on two's complement representations (&, |, ^, `and_not`), so this makes sense for consistency.

(In some ways the two's complement format is better, I'm toying with the idea of switching to it because it will make certain bitwise operations much faster).

**Comment by cmpute** [comment]
Wow, that's an interesting idea, are you talking about using `2^(WORD_BITS*n) - N` to represent the negative integers? In that case the behavior of trailing_zeros totally changed, it's no longer equivalent to this:

https://github.com/tczajka/ibig-rs/blob/f1588d8758872db0300a6f5ff1a5a77771c16b6a/src/bits.rs#L215

Is there any plan to use that representation in the near future? I'm currently also trying to implement an arbitrary precision float library based on ibig, I would like to have some efficient way to convert between UBig and IBig

**Comment by tczajka** [comment]
> Wow, that's an interesting idea, are you talking about using `2^(WORD_BITS*n) - N` to represent the negative integers?

Yes.

> In that case the behavior of trailing_zeros totally changed, it's no longer equivalent to this: [...]

It's the same thing. For example, -12 is two's complement is: ....1110100. Two trailing zeros, -12 is divisible by 4.

Except it should say "largest n" not "smallest n"! Fixing this.

**Comment by tczajka** [comment]
> I would like to have some efficient way to convert between UBig and IBig

I don't know what you mean by this. `IBig` already implements `From<UBig>`, and `UBig` already implements `TryFrom<IBig>`.

**Comment by cmpute** [comment]
> > I would like to have some efficient way to convert between UBig and IBig
> 
> I don't know what you mean by this. `IBig` already implements `From<UBig>`, and `UBig` already implements `TryFrom<IBig>`.

My bad, I actually want to use something like `IBig::magnitude()` outside ibig, i.e. take reference of the absolute value without copying, but this might be infeasible if IBig is represented in 2's complement.

Do you have any rough performance measurements? I just searched around and didn't find any useful information about using 2's complement for big integers.

> It's the same thing. For example, -12 is two's complement is: ....1110100. Two trailing zeros, -12 is divisible by 4.
>
> Except it should say "largest n" not "smallest n"! Fixing this.

Thanks, I didn't realize that trailing zeros are the same for negative values, going to close this issue.
