### ISSUE TITLE
Question: Conversion from Modulo to UBig?

### ISSUE THREAD

**Issue by SilentVoid13** [tczajka/ibig-rs#17]
I want to perform some arithmetic operations in a ModuloRing then use `to_be_bytes` on the result.
This is only available on `UBig` but I couldn't find a way to convert a `Modulo` to a `UBig`.

**Comment by tczajka** [comment]
Use [Modulo::residue](https://docs.rs/ibig/0.3.6/ibig/modular/struct.Modulo.html#method.residue).

**Comment by SilentVoid13** [comment]
Totally missed that, thank you!
