### ISSUE TITLE
0 shouldn't have a modular inverse

### ISSUE THREAD

**Issue by cmpute** [tczajka/ibig-rs#18]
As title says. The reason is the same as why division by zero is not permitted.

**Comment by tczajka** [comment]
Correct. `inverse` should return `None` (except for the trivial ring modulo 1 where the only element is its own inverse).

Do you have example code that fails?

**Comment by cmpute** [comment]
Ah I noticed that in your test, but I didn't think about that `0^-1 = 0  mod 1`, I don't have a failure case for other modulo, it's my mistake :rofl:
