### ISSUE TITLE
UBig and IBig maybe should implement ToPrimitive from num_traits

### ISSUE THREAD

**Issue by edg-l** [tczajka/ibig-rs#19]
Right now there is no way to convert them to primitive types AFAIK, it could be done through such trait.

https://docs.rs/num-traits/0.2.15/num_traits/cast/trait.ToPrimitive.html

**Comment by tczajka** [comment]
You can convert to a primitive using the `TryFrom` or `TryInto` traits:
```
let a: UBig = ubig!(100);
let b: u32 = a.try_into().unwrap();
```
