### ISSUE TITLE
Differences between num-bigint?

### ISSUE THREAD

**Issue by pickfire** [tczajka/ibig-rs#2]
Is there other differences other than performance? And, why not just improve num-bigint rather than creating a new crate?

**Comment by tczajka** [comment]
It has guaranteed memory use: small numbers never use memory on the heap, large numbers never have more than 25% of memory overhead.

There is a new type for modular arithmetic in the works.

The performance is particularly optimized for very large numbers (think millions of digits).

The implementation is not a fork of num-bigint, it's designed from scratch. It would have taken forever to rewrite num-bigint like this via incremental changes. It could potentially just be switched to using ibig as the backend, especially if very large number performance is important -- it doesn't seem to have really been designed with that in mind.

**Comment by pickfire** [comment]
It is possible to list this down in README as a FAQ? At least others can compare the differences.
