### ISSUE TITLE
Montgomery modular operations?

### ISSUE THREAD

**Issue by cmpute** [tczajka/ibig-rs#9]
Hi Tomek, thanks for your great work on this crate!

I was planning to add `ibig` as one of the backend of my [`num-modular`](https://crates.io/crates/num-modular) crate and found that, the support for fast modular arithmetic operations is implemented with "invariant integers". I wonder if this algorithm is more efficient than using Montgomery form? If not, I'm willing to implement Montgomery form for ibig 😄

**Comment by cmpute** [comment]
IBig internally use fast division by inverse, which is not as fast as Montgomery, but it's already pretty efficient.

**Comment by tczajka** [comment]
Last time I thought about this, it seemed like this could be an improvement, but not a huge improvement, and only in a certain range -- for medium-sized numbers, not for super-large numbers. So it would require splitting the representation for different modulo sizes. That might be a feasible idea, it was actually on my list to try.
